# Generated by Django 5.1.7 on 2025-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
                ('PHONE', models.IntegerField()),
                ('Movie_Name', models.CharField(max_length=200)),
                ('Amount', models.IntegerField()),
                ('Genre', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('Rating', models.FloatField(help_text="From '0.0' to '5.0'")),
            ],
        ),
    ]
